-- Crear tabla para almacenar las respuestas del formulario
CREATE TABLE IF NOT EXISTS formularios_consentimiento (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(255),
    apellido VARCHAR(255),
    menor_edad VARCHAR(10),
    nombre_tutor VARCHAR(255),
    telefono_tutor VARCHAR(20),
    relacion VARCHAR(100),
    fecha_nacimiento DATE,
    edad INT,
    genero VARCHAR(20),
    correo VARCHAR(255),
    direccion TEXT,
    ciudad VARCHAR(100),
    estado VARCHAR(100),
    zipcode VARCHAR(10),
    telefono_casa VARCHAR(20),
    telefono_celular VARCHAR(20),
    telefono_trabajo VARCHAR(20),
    contacto_emergencia VARCHAR(255),
    telefono_emergencia VARCHAR(20),
    quejas TEXT,
    otros_quejas TEXT,
    afirmaciones TEXT,
    otros_afirmaciones TEXT,
    embarazada VARCHAR(10),
    diabetico VARCHAR(10),
    fumador VARCHAR(10),
    drogas VARCHAR(10),
    drogas_frecuencia TEXT,
    renal VARCHAR(10),
    insuficiencia VARCHAR(10),
    anticoagulantes VARCHAR(10),
    cancer VARCHAR(10),
    alergico VARCHAR(10),
    medicamento_alergico TEXT,
    condicion_medica VARCHAR(10),
    condicion_explicacion TEXT,
    medicamentos_recetados TEXT,
    medicamentos_venta_libre TEXT,
    suplementos TEXT,
    firma_paciente MEDIUMTEXT,
    firma_doctor MEDIUMTEXT,
    estado_revision ENUM('pendiente', 'aprobado', 'rechazado') DEFAULT 'pendiente',
    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    fecha_revision TIMESTAMP NULL,
    comentarios_doctor TEXT
);

-- Crear tabla para usuarios (doctores)
CREATE TABLE IF NOT EXISTS usuarios (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL,
    apellido VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    rol ENUM('doctor', 'admin') DEFAULT 'doctor',
    activo BOOLEAN DEFAULT true,
    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ultima_sesion TIMESTAMP NULL,
    UNIQUE KEY unique_email (email)
); 